### PR TITLE
Fix Cloud Debugger [WIP]

### PR DESCRIPTION
**Pull request by meltsufin**
I'm not sure why, but reverting the `jetty.comands` file to the way it was before logging PR was merged in, fixes the Cloud Debugger functionality.

Fixes issue #174 

@gregw Any clues?

### CODE REVIEW

**Comment by gregw** [comment]
I expect this is because JUL logging requires a second JVM to be started and the debugger is debugging the original JVM rather than the spawned one.

**Comment by meltsufin** [comment]
@gregw This sounds like a good lead. I didn't know that JUL requires a second JVM. Is that something the Jetty module does?

**Comment by meltsufin** [comment]
@gregw I can't seem to find the code for the logging-jul module anywhere. Can you point me to where this whole second JVM starting is happening? Thanks!

**Comment by jmcc0nn3ll** [comment]
I think it would be spawned off by the use of --exec somewhere in the jetty.command file (think that is the right file), or the vm that shows up after executing the jetty.command since I think that file was generated by a jvm call to start.jar --dry-run or something?

**Comment by meltsufin** [comment]
Superseded by #183

**Pull request closed without merging**
