### PR TITLE
Issue #4 Revert to default jetty logging

### PR DESCRIPTION
**Pull request by gregw**
Reverted to default jetty logging.  Tested with [async-rest](https://github.com/jetty-project/java-docs-samples/tree/gcloud-jetty-runtime-4/managed_vms/async-rest) example, which is currently running at https://jetty9-work.appspot.com/ and the logs produced can be seen on the [console](https://console.cloud.google.com/logs/viewer?project=jetty9-work&authuser=1&key1=default&minLogLevel=0&expandAll=false&resource=appengine.googleapis.com%2Fmodule_id%2Fdefault%2Fversion_id%2F20160914t162607&logName=projects%2Fjetty9-work%2Flogs%2Fappengine.googleapis.com%252Fstderr&lastVisibleTimestampNanos=1473835164000000000).

### CODE REVIEW

**Comment by gregw** [comment]
see also https://github.com/GoogleCloudPlatform/java-docs-samples/pull/338

**Comment by meltsufin** [comment]
What will happen to Jetty logging if the `resources/jetty-logging.properties` is not there at all?

**Comment by joakime** [comment]
It would be discovered.

 1. Slf4jLog - used if slf4j-api is present on server side
 2. StdErrLog - used if slf4j-api is not present
 3. JavaUtilLog - never used

It would also make configuring it strange for people that want to change the behavior.
(_"where do I enable log4j? where can I set the logging levels? how can i see the stacktraces?"_ etc)

**Comment by joakime** [comment]
Would recommend leaving `resources/jetty-logging.properties` in place.

It's going to be required in the long run anyway.  

Once any of the following becomes true:

 1. We use the Google Cloud Logging API
 2. We want to use java.util.logging
 3. We want to support `logging.properties` on the application deployment

This PR should be considered "a short term hack".

**Comment by meltsufin** [comment]
My question was more about the lines that are staying in jetty-logging.properites. Are they changing any defaults?
```
org.eclipse.jetty.LEVEL=INFO
org.eclipse.jetty.SOURCE=false
org.eclipse.jetty.STACKS=true
org.eclipse.jetty.LONG=false
```

**Comment by gregw** [comment]
@meltsufin those are the defaults, so yes we can just delete the file, as it is essentially documentation. Any change to the file needs to replace the file in a subsequent docker image, and I have an example of doing that in [the sample app](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/338)

I'll remove

**Comment by meltsufin** [comment]
LGTM

**Comment by meltsufin** [comment]
@gregw I noticed that `java-util-logging.properties` is still there. Was it supposed to be removed as part of this PR?

**Comment by gregw** [comment]
@meltsufin yes that file is no longer used.  Originally it was used if the `jetty-logging.properties` configured JUL logging, but as we have removed `jetty-logging.properties`  we should also remove `java-util-logging.properties`

**Pull request merged**
