### PR TITLE
Moves setting RUNTIME_DIR to runtime, instead of openjdk image.

### PR DESCRIPTION
**Pull request by joaoandremartins**
Helps fixing https://github.com/GoogleCloudPlatform/openjdk-runtime/issues/64

### CODE REVIEW

**Comment by joaoandremartins** [comment]
Still need to set `APP_WEB_INF_DIR` here.

**Comment by meltsufin** [comment]
@joaoandremartins I think we should first submit the code change for  `format-env-appengine-vm.sh` as suggested in my last comment in GoogleCloudPlatform/openjdk-runtime#64, and then simply set `CDBG_APP_WEB_INF_DIR` here.

**Comment by joaoandremartins** [comment]
This change is pending internal change 155509870 from being submitted and published.

**Comment by meltsufin** [comment]
@joaoandremartins I think we need to update this PR/resolve conflicts.

**Comment by joaoandremartins** [comment]
I'm waiting for the changes in the CDBG agent to be released before moving on further work here.

I noticed this morning that they haven't been published yet.

**Comment by joaoandremartins** [comment]
@meltsufin @aslo PTAL

**Pull request merged**
