### PR TITLE
add l.gcr.io/google/jetty path to readme

### PR DESCRIPTION
**Pull request by nkubala**
also, fix typo in code formatting.

@meltsufin  @dlorenc

### CODE REVIEW

**Comment by meltsufin** [comment]
@nkubala Can you resolve conflicts with master or recreate this PR please? Thanks!

**Comment by nkubala** [comment]
@meltsufin rebased and fixed the path in a few places. PTAL

**Comment by nkubala** [comment]
@meltsufin you'll have to merge this for me, whenever you get a chance.

**Comment by meltsufin** [comment]
Yep, thanks!

**Pull request merged**
